model_name_or_path: FacebookAI/xlm-roberta-base

train_dataset: data/daily_dialog_train.jsonl
validation_dataset: data/daily_dialog_validation.jsonl
test_datasets: 
  - data/daily_dialog_test.jsonl
  - data/mutual_validation.jsonl

output_dir: results/xlmroberta
do_train: false
do_eval: false
do_predict: true


per_device_train_batch_size: 32
per_device_eval_batch_size: 32
gradient_accumulation_steps: 2

learning_rate: 5e-5
warmup_steps: 200
num_train_epochs: 8


logging_steps: 100

bf16: false
fp16: true # XLM-Roberta was trained with fp16